"""add profile

Revision ID: 538abdc5aefe
Revises: 001f87525808
Create Date: 2026-07-06 17:06:42.043268

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: Union[str, None] = "538abdc5aefe"
down_revision: Union[str, None] = "001f87525808"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("first_name", sa.String(length=150), nullable=True),
        sa.Column("last_name", sa.String(length=150), nullable=True),
        sa.Column("phone_number", sa.String(length=32), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["auth_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_auth_profiles_user_id"), "auth_profiles", ["user_id"], unique=True
    )
    op.drop_column("auth_users", "first_name")
    op.drop_column("auth_users", "last_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth_users",
        sa.Column(
            "last_name", sa.VARCHAR(length=150), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "auth_users",
        sa.Column(
            "first_name", sa.VARCHAR(length=150), autoincrement=False, nullable=True
        ),
    )
    op.drop_index(op.f("ix_auth_profiles_user_id"), table_name="auth_profiles")
    op.drop_table("auth_profiles")
    # ### end Alembic commands ###
