"""test

Revision ID: b918b4d48cb0
Revises: 538abdc5aefe
Create Date: 2026-07-07 12:21:00.303334

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: Union[str, None] = "b918b4d48cb0"
down_revision: Union[str, None] = "538abdc5aefe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
